"""Viewer rendering constants shared by viewer modules."""

SKETCH_DISPLAY_OFFSET = 1.5
SKETCH_ENTITY_DISPLAY_OFFSET = 2.5
SKETCH_PLANE_OFFSET = 1.5
SKETCH_MARKER_OFFSET = 2.2
SKETCH_PREVIEW_OFFSET = 2.5
PREVIEW_POLYGON_OFFSET_FACTOR = -8.0
PREVIEW_POLYGON_OFFSET_UNITS = -8.0
